strings = {
    'str NaN': 'NaN',
    'str none': 'None',
    'str true': 'True',
    'str false': 'False',
    'str 0': '0',
    'str -1': '-1',
    'str -1.5': '-1.5',
    'str 0.42': '0.42',
    'str .42': '.42',
    'str 1.2E+9': '1.2E+9',
    'str 1.2e8': '1.2e8',
    'str 0xFF': '0xFF',
    'str Inf..': 'Infinity',
    'str empty': '',
    'str space': ' ',
    'str [Ob]': '[object Object]',
    'str dot': '.',
    'str +': '+',
    'str -': '-',
    'str 99,999': '99,999',
    'str date': '2077-09-08',
    'str #abcdef': '#abcdef',
    'str 1.2.3': '1.2.3',
    'str blah': 'blah',
}
